version: '3'

env:
  CGO_ENABLED: '0'
  GOAMD64: v3

tasks:
  build:
    cmds:
      - go build -o bin/ydn -v .
    generates:
      - bin/ydn

  image:
    deps: [build]
    cmds:
      - podman build . -t ydn
    sources:
      - Containerfile
      - bin/ydn

  push:
    deps: [image]
    cmds:
      - podman tag ydn $USER/ydn:latest
      - podman tag ydn $USER/ydn:$(date +"%Y%m%d-%H%M%S")
      - podman push $USER/ydn:latest docker.io/$USER/ydn --creds=$USER

  rollout:
    cmds:
      - kubectl rollout restart deployment/ydn-app
